---
# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
name: License Header Check

"on": [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  license-header-check:
    name: License Header Check
    # yamllint disable-line rule:line-length
    uses: linuxfoundation/lfx-public-workflows/.github/workflows/license-header-check.yml@a93335d2abc2a2e2bb1b7a4cdefbbf15351681ce  # v0.1.0
    with:
      copyright_line: "Copyright The Linux Foundation and each contributor to LFX."
      exclude_pattern: "gen/*,cmd/voting-api/kodata/*"
